name: 18f-identity
full_name: Consumer Identity Services
description: 18F development of consumer identity solutions
impact: Make it easy for citizens to verify their identity in order to obtain information or services from government agencies.
owner_type: project
stage: alpha
testable: false
partners:
 - GSA, USDS, Various Agencies
contact:
 - url: mailto:diego.mayer@gsa.gov
   text: diego.mayer@gsa.gov
type: app
