disposable_email_services:
  - courtsidemail.com
  - eyamail.com
  - fileright.net
  - immigrationdirect.com
  - kingfishmail.com
  - speedstermail.com
  - sprintpostmail.com
  - usimmigrationemail.com
